import { useEffect, useState, FormEvent } from 'react';
import toast from 'react-hot-toast';
import { Plus, Star, Check, X, Trash2 } from 'lucide-react';
import type { Opportunity, OpportunityCategory } from '@/types';
import { useConfirmDialog } from '@/components/ui/ConfirmDialog';
import { supabase, isSupabaseConfigured } from '@/lib/supabase';

export function AdminOpportunities() {
  const [items, setItems] = useState<Opportunity[]>([]);
  const [categories, setCategories] = useState<OpportunityCategory[]>([]);
  const [showForm, setShowForm] = useState(false);
  const { confirm, dialog } = useConfirmDialog();
  useEffect(() => { if (!isSupabaseConfigured) return; (async () => { const [{ data }, { data: cats }] = await Promise.all([supabase.from('opportunities').select('*').order('created_at', { ascending: false }), supabase.from('opportunity_categories').select('*').order('name')]); if (data) setItems(data as Opportunity[]); if (cats) setCategories(cats as OpportunityCategory[]); })(); }, []);
  async function updateStatus(id: string, publish: boolean) { const patch = { status: publish ? 'published' : 'draft', verification_status: publish ? 'verified' : 'closed' }; if (isSupabaseConfigured) { const { error } = await supabase.from('opportunities').update(patch).eq('id', id); if (error) { toast.error(error.message); return; } } setItems((prev) => prev.map((o) => o.id === id ? { ...o, ...patch } : o)); toast.success(publish ? 'Opportunity approved and published' : 'Opportunity rejected'); }
  async function toggleFeature(id: string) { const target = items.find((o) => o.id === id); if (!target) return; const next = !target.featured; if (isSupabaseConfigured) { const { error } = await supabase.from('opportunities').update({ featured: next }).eq('id', id); if (error) { toast.error(error.message); return; } } setItems((prev) => prev.map((o) => o.id === id ? { ...o, featured: next } : o)); }
  function remove(o: Opportunity) { confirm({ title: 'Delete opportunity', description: `Delete "${o.title}"? This can't be undone.`, confirmLabel: 'Delete', danger: true, onConfirm: async () => { if (isSupabaseConfigured) { const { error } = await supabase.from('opportunities').delete().eq('id', o.id); if (error) { toast.error(error.message); return; } } setItems((prev) => prev.filter((x) => x.id !== o.id)); toast.success('Deleted'); } }); }
  async function onCreate(e: FormEvent<HTMLFormElement>) { e.preventDefault(); const fd = new FormData(e.currentTarget); const title = String(fd.get('title') || '').trim(); const payload = { title, slug: `${title.toLowerCase().replace(/[^a-z0-9]+/g, '-').replace(/(^-|-$)/g, '')}-${Date.now()}`, description: String(fd.get('description') || ''), category_id: String(fd.get('category_id') || '') || null, platform_name: String(fd.get('platform') || '') || null, requirements: null, how_to_start: String(fd.get('how_to_start') || '') || null, earning_estimate: String(fd.get('earning') || '') || null, application_url: String(fd.get('url') || '') || null, country_eligibility: 'Pakistan', verification_status: 'needs_review', status: 'draft', featured: false }; if (isSupabaseConfigured) { const { data, error } = await supabase.from('opportunities').insert(payload).select().single(); if (error) { toast.error(error.message); return; } setItems((prev) => [data as Opportunity, ...prev]); } setShowForm(false); e.currentTarget.reset(); toast.success('Opportunity added — ready for review'); }
  return <div className="space-y-6">{dialog}<div className="flex items-center justify-between"><div><h1 className="font-display text-2xl font-extrabold text-navy-900">Opportunities</h1><p className="text-sm text-navy-500">Add, approve, feature, or remove listings.</p></div><button className="btn-primary" onClick={() => setShowForm((s) => !s)}><Plus size={16} /> Add opportunity</button></div>{showForm && <form onSubmit={onCreate} className="card grid gap-3 p-5 sm:grid-cols-2"><input name="title" required placeholder="Title" className="input sm:col-span-2" /><input name="platform" placeholder="Platform / company" className="input" /><select name="category_id" className="input"><option value="">Category</option>{categories.map((c) => <option key={c.id} value={c.id}>{c.name}</option>)}</select><textarea name="description" required placeholder="Description" className="input sm:col-span-2" rows={2} /><textarea name="how_to_start" placeholder="How to start" className="input sm:col-span-2" rows={2} /><input name="earning" placeholder="Estimated earning" className="input" /><input name="url" type="url" placeholder="Application URL" className="input" /><div className="sm:col-span-2 flex gap-2"><button className="btn-primary">Save</button><button type="button" onClick={() => setShowForm(false)} className="btn-outline">Cancel</button></div></form>}<div className="card overflow-x-auto"><table className="w-full text-sm"><thead className="bg-navy-50 text-left text-xs font-semibold uppercase text-navy-500"><tr><th className="px-5 py-3">Title</th><th className="px-5 py-3">Category</th><th className="px-5 py-3">Status</th><th className="px-5 py-3">Featured</th><th className="px-5 py-3">Actions</th></tr></thead><tbody className="divide-y divide-navy-100">{items.map((o) => <tr key={o.id}><td className="px-5 py-3 font-medium text-navy-900">{o.title}</td><td className="px-5 py-3 text-navy-600">{o.category ?? categories.find((c) => c.id === o.category_id)?.name ?? 'Uncategorized'}</td><td className="px-5 py-3"><span className={`badge capitalize ${o.status === 'published' ? 'bg-brand-green/10 text-brand-green-dark' : 'bg-brand-amber/10 text-amber-700'}`}>{o.status === 'published' ? 'published' : 'review'}</span></td><td className="px-5 py-3"><button onClick={() => toggleFeature(o.id)}><Star size={16} className={o.featured ? 'fill-brand-amber text-brand-amber' : 'text-navy-300'} /></button></td><td className="px-5 py-3"><div className="flex gap-2">{o.status !== 'published' && <button onClick={() => updateStatus(o.id, true)} className="rounded-lg bg-brand-green/10 p-1.5 text-brand-green-dark" title="Approve"><Check size={15} /></button>}{o.status === 'published' && <button onClick={() => updateStatus(o.id, false)} className="rounded-lg bg-red-50 p-1.5 text-red-600" title="Reject"><X size={15} /></button>}<button onClick={() => remove(o)} className="rounded-lg bg-navy-50 p-1.5 text-navy-500"><Trash2 size={15} /></button></div></td></tr>)}</tbody></table></div></div>;
}
